<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="dvtcstests048" failures="1" tests="1" name="Test15" time="830.212" errors="0" timestamp="2024-04-16T15:11:25 IST">
  <testcase classname="testscripts.scenario1.Vandalism_Proxy_DamageCausedByAnotherVehicle_TU" name="runTC1" time="830.113">
    <failure type="java.lang.AssertionError" message="Refreshed and retried for 1.30 min">
      <![CDATA[java.lang.AssertionError: Refreshed and retried for 1.30 min
at supportlibraries.DriverScript.wrapUp(DriverScript.java:658)
at supportlibraries.DriverScript.driveTestExecution(DriverScript.java:121)
at testscripts.scenario1.Vandalism_Proxy_DamageCausedByAnotherVehicle_TU.runTC1(Vandalism_Proxy_DamageCausedByAnotherVehicle_TU.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- runTC1 -->
</testsuite> <!-- Test15 -->
